
INSERT INTO users (username, name, email, password, enabled) VALUES ('user', 'user', 'user@hotmail.com', '$2a$12$pj5F6KLWefdJdvLsMQYCq.EwAJibZGI3.WllsLd/UcIhb/Txnjele', TRUE);
INSERT INTO userprofile (id, user_username, total_completed_habits, total_habits, user_start_date) VALUES (100, 'user', 0, 0, TO_DATE('10/06/2022', 'DD/MM/YYYY'));

INSERT INTO users (username, name, email, password, enabled) VALUES ('admin', 'admin', 'admin@hotmail.com', '$2a$12$pj5F6KLWefdJdvLsMQYCq.EwAJibZGI3.WllsLd/UcIhb/Txnjele', TRUE);
INSERT INTO adminprofile (id, user_username) VALUES (100, 'admin');

INSERT INTO authorities (username, authority) VALUES ('user', 'ROLE_USER');
INSERT INTO authorities (username, authority) VALUES ('admin', 'ROLE_ADMIN');

-- INSERT INTO userhabits(id, completed, name, type, user_id)
-- VALUES (100, false, 'workout', 'sport', 100);

-- INSERT INTO userrewards(id, description, name, type, user_id)
-- VALUES (100, 'Creating your first habit', 'habit-1', 'pink', 100);

INSERT INTO adminrewards (id, name, description, type, admin_id)
VALUES (100, 'habit-1', 'Creating your first habit', 'pink', 100),
        (101, 'habit-10', 'Creating a total of 10 habits', 'green', 100),
       (102, 'habit-50', 'Creating a total of 50 habits', 'yellow', 100),
       (103, 'habit-100', 'Creating a total of 100 habits', 'blue', 100),
       (104, 'habit-200', 'Creating a total of 200 habits', 'purple', 100);


INSERT INTO adminhabits (id, name, description, type, admin_id)
VALUES (100, 'workout', 'Workout for 30 minutes every day', 'sport', 100),
       (101, 'cook', 'Cook a meal every day', 'food', 100),
       (102, 'read', 'Read 50 pages of a book every day', 'mind', 100),
       (103, 'stop smoking', 'Don`t smoke every day', 'health', 100),
       (104, 'Save 1 dollar', 'Try to save 1 dollar every day', 'finance', 100),
       (105, 'Make the bed', 'Make the bed before you leave', 'home', 100),
       (106, 'Journaling', 'Write something in your journal', 'mind', 100),
       (107, 'Say I love you', 'Tell a family member or friend you love them', 'family', 100),
       (108, 'Complete homework', 'Complete an assignment', 'study', 100),
       (109, 'Relaxing', 'Completely relax for an hour', 'mind', 100),
       (110, 'Water plants', 'Water the plants that need water', 'home', 100),
       (111, 'Take medication', 'Take in your daily medication', 'health', 100),
       (112, 'Bake something', 'Try to bake something', 'food', 100),
       (113, 'Meditate', 'Meditate for a minimum of 10 minutes', 'mind', 100),
       (114, 'Paying bills', 'Pay all the bills you need to pay.', 'finance', 100),
       (115, 'Skin care', 'Take the time today to care for your skin.', 'health', 100),
       (116, 'no alcohol', 'Do not drink alcohol today. You can do this! ', 'health', 100),
       (117, 'eat fruit', 'Eat a piece of fruit today', 'food', 100),
       (118, 'no caffeine', 'Do not take any caffeine today.', 'health', 100),
       (119, 'learn something', 'Take your time today to learn something new.', 'mind', 100),
       (120, 'call someone', 'Call a friend or family member today', 'family', 100),
       (121, 'take a walk', 'Take a walk today outside', 'sport', 100),
       (122, 'write a goal', 'Write a goal down today. It can be anything!', 'business', 100),
       (123, 'learn for exam', 'Learn for an exam. Do not forget the Pomodoro Technique.', 'study', 100),
       (124, 'stretch your legs', 'Stretch your legs every now and then.', 'sport', 100),
       (125, 'Check email', 'Check your email today. Do not forget the spam!', 'business', 100),
       (126, 'draw something', 'Draw something. It can be anything you want.', 'hobby', 100),
       (127, 'vacuum', 'Vacuum at least one room in your house today. Keep it clean!', 'home', 100),
       (128, 'paint something', 'Paint something today. It Can be anything!', 'hobby', 100),
       (129, 'Yoga', 'Do a yoga workout today.', 'sport', 100),
       (130, 'eat breakfast', 'Eat some breakfast today.', 'food', 100),
       (131, 'limit social media', 'Pick a maximum time you will spend on social media.', 'mind', 100),
       (132, 'track you sleep', 'Track your sleep by writing it down or using an app.', 'health', 100),
       (133, 'give a compliment', 'Give someone a compliment.', 'family', 100),
       (134, 'eat vegetables', 'Eat vegetables today with at least one meal.', 'food', 100),
       (135, 'Drink 2L water', 'Drink at least 2 liter water.', 'health', 100),
       (136, 'Create to-do', 'Create a to do list for the next day.', 'business', 100),
       (137, 'do the dishes', 'To the dishes today.', 'home', 100),
       (138, 'smile to a stranger', 'Smile to a stranger today.', 'family', 100),
       (139, 'wash your hands', 'Wash your hand multiple times a day.', 'health', 100),
       (140, 'be positive', 'Have a positive thought about something.', 'mind', 100),
       (141, 'make a smoothie', 'Make a smoothie today.', 'food', 100),
       (142, '10.000 steps', 'Walk at least 10.000 steps today.', 'sport', 100),
       (143, 'learn a language', 'Learn a new language.', 'mind', 100),
       (144, 'Listen to music', 'Listen to calming music or music of your choice.', 'mind', 100),
       (145, 'writ a blog post', 'Create and write your own blog.', 'hobby', 100),
       (146, 'floss', 'Floss your teeth to keep them healthy.', 'health', 100),
       (147, 'smile', 'Smile today!', 'mind', 100),
       (148, 'eat smaller meals', 'Eat five to six smaller meals instead of three heavy meals.', 'food', 100),
       (149, 'dance', 'Dance to at least one song.', 'sport', 100),
       (150, 'check subscriptions', 'Check your subscriptions today.', 'finance', 100),
       (151, 'food diary', 'Keep a food diary to understand what your eating.', 'food', 100),
       (153, 'meal prep', 'Prep your meals today.', 'food', 100),
       (154, 'Early to rise', 'Start your day early in the morning.', 'health', 100),
       (155, 'take out the trash', 'Take out the trash today.', 'home', 100),
       (156, 'no spending', 'Do not spend any money today.', 'finance', 100),
       (157, 'squats', 'Do at least 20 squats today.', 'sport', 100),
       (158, 'mind tracking', 'Write down how you feel today.', 'mind', 100),
       (159, 'do the laundry', 'Do the laundry today and try to keep those boxes empty!', 'home', 100),
       (160, 'thank someone', 'Thank someone today.', 'family', 100),
       (161, 'study', 'Study for at least one hour', 'study', 100),
       (162, 'take a photo', 'Take a photo of something today.', 'hobby', 100),
       (163, 'no phone to bed', 'Do not use your phone before going to bed', 'mind', 100),
       (164, 'explore music', 'Listen to an music artist you do not know yet.', 'hobby', 100),
       (165, 'focus on work', 'Focus a whole hour on work without distracting yourself.', 'business', 100),
       (166, 'take a breath', 'Take a deep breath a few times.', 'mind', 100),
       (167, 'go to the gym', 'Go to the gym today.', 'sport', 100),
       (168, 'brush your teeth', 'Brush your teeth at least 2 times a day.', 'health', 100),
       (169, 'healthy meal', 'Make a healthy meal today.', 'food', 100),
       (170, 'network', 'Try to network with someone online or in person.', 'business', 100),
       (171, 'credit card', 'Reduce your credit card dept.', 'finance', 100),
       (172, 'learn a new word', 'Learn a new word today.', 'mind', 100),
       (173, 'cold shower', 'Take a cold shower today.', 'health', 100),
       (174, 'write a book', 'Write a book about anything you want.', 'hobby', 100),
       (175, 'sudoku', 'Complete a sudoku puzzle.', 'mind', 100),
       (176, 'push-ups', 'Do at least 10 push-ups today.', 'sport', 100),
       (177, 'side hustle', 'Work on a side hustle.', 'business', 100),
       (178, 'check to-do', 'Check all your to-dos of the day or the week. ', 'business', 100),
       (179, 'have a talk', 'Start a conversation with someone.', 'family', 100),
       (180, 'avoid sugar', 'Avoid sugar in meals or drinks today.', 'food', 100),
       (181, 'make an assignment', 'Start or finish an assigment today.', 'study', 100),
       (182, 'Out of comfort', 'Do something out of your comfort zone.', 'mind', 100),
       (183, 'Check calender', 'Check your calender today for any appointments or other activities.', 'business', 100),
       (184, 'play an instrument', 'Learn to play an instrument.', 'hobby', 100),
       (185, 'No junk food', 'Avoid eating junk food today.', 'food', 100),
       (186, 'Clean up', 'Clean up at least one room in the house.', 'home', 100),
       (187, 'spend time', 'Spend some time with someone you love.', 'family', 100),
       (188, 'invest', 'Invest in something. The amount does not matter.', 'business', 100),
       (189, 'think before buying', 'Think before buying anything.', 'finance', 100),
       (190, 'walk your dog', 'Walk your dog at least 3 times a day.', 'sport', 100),
       (191, 'Take the bike', 'Take the bike to work or any other location.', 'sport', 100),
       (192, 'Send a sweet text', 'Text something sweet to someone.', 'family', 100),
       (193, 'playing a game', 'Relax a little and play some games.', 'hobby', 100),
       (194, 'review budget', 'Check your budget and review how you have done.', 'finance', 100),
       (195, 'paint', 'Paint something you want.', 'hobby', 100),
       (196, 'tudor', 'Tudor someone or get a tudor.', 'study', 100),
       (197, 'pay off dept', 'Try to pay off any dept.', 'finance', 100),
       (198, 'life coach', 'Talk to a life coach.', 'mind', 100),
       (199, 'pomodoro technique', 'Use the Pomodoro Technique when you study.', 'study', 100),
       (200, 'course', 'Take a course.', 'study', 100);

